my_str=input("\n Enter Your String:-")
index=input("\n Your Can Chose Your Any Index Value:-")
print(my_str.index(index))
find=input("\n You Can Chose Your Finding Value:-")
print(my_str.find(find))
print("\n Upper Check")
print(my_str.isupper())
flag=True
print("\n Lower Check")
print(my_str.islower())
flag=True
print("\n Your String convert Lower Case To Upper Case")
print(my_str.upper())
print("\n Your String Conver Upper Case To Lower Case")
print(my_str.lower())
strip=input("\nYour striping Element:-")
print(my_str.strip(strip))
leftstrip=input("\n Only Left value striping:-")
print(my_str.lstrip(leftstrip))
rightstrip=input("\n Only Right Value striping:-")
print(my_str.rstrip(rightstrip))
print("\n Your Total String Length")
print(len(my_str))

